### ISSUE TITLE
filter_vcf does not recognise vcf structure

### ISSUE THREAD

**Issue by LaraUrban** [enormandeau/stacks_workflow#32]
Hi @enormandeau, 

Thanks for providing this convenient code. 

I however run into an issue when I try to filter my vcf files:

Traceback (most recent call last):
  File "../../1_filter_vcf.py", line 910, in <module>
    ind_info = get_individual_info(l)
  File "../../1_filter_vcf.py", line 243, in get_individual_info
    population, sample = l[i]
ValueError: need more than 1 value to unpack

I checked and my vcf file should have the appropriate structure. Do you know what might be happening here? Many thanks!

**Comment by enormandeau** [comment]
Hi Lara,

The first thing to know is that my script will work only on the outputs from STACKS ~1.32 to 1.48. I never tried it with STACKS 2.0+ and I know that it breaks with STACKS VCF files that have been filtered with other tools, for example vcftools.

However, from what I see in your error message, I think your samples are not named in a way that the script will recognize. The sample names must have the format `pop_sample`, with the population name before the underscore and sample name after. This is required by the script.

**Comment by LaraUrban** [comment]
Thanks for your very quick response, @enormandeau !

Version and pre-processing should be fine, so it might just be the sample names. I will check and close the issue if that was the problem. Many thanks!

**Comment by LaraUrban** [comment]
That solved it, many thanks!
