### ISSUE TITLE
Clean RAD Seq data

### ISSUE THREAD

**Issue by kawu001** [enormandeau/stacks_workflow#36]
Hi,
I just got my ddRadseq data, without barcodes and RE. The company said it is a clean data. How can I adapt this script to analyze my data?

Thank you.

**Comment by enormandeau** [comment]
On don't think you will need to "adapt" anything. It should work directly if you put your samples in the 04-all_samples folder. Is your dataset single-end or paired-end? Are you using a reference genome? I suggest you go with the latest STACKS version.

**Comment by kawu001** [comment]
Thanks for your response. My data is paired-end reads and I want to use the de-novo approach. Like I said previously, no barcodes and no RE, do you think I still need to start with the process_radtags or proceed to the de-novo mapping since it is a cleaned data.

**Comment by enormandeau** [comment]
No, you need to put the samples in the `04-all_samples` folder and start directly with the stacks scripts. I have never used paired-end data. Please read the information in the STACKS documentation to know the proper steps and what to do with your paired-end data:

https://catchenlab.life.illinois.edu/stacks/manual/

**Comment by kawu001** [comment]
Thanks! I will update you as it goes.
