### ISSUE TITLE
stacks v2.0 vcf output lacks AD for some samples

### ISSUE THREAD

**Issue by Carol-Symbiomics** [enormandeau/stacks_workflow#37]
Hi!
I was wondering if this issue was ever solved in the newer version of stacks. I've checked the log files for the bugs fixed but unfortunately, I couldn't find anyone related to the mentioned problem.
Funny enough, when I try to use the same vcf file output by stacks 2.0 in the pipeline with my list of filtered SNPs, Stacks complains about the Allele depth (AD) error and throws away a bunch of my whitelisted markes.
please let me know if the latest version of stacks addressed this issue, in that case would it be possible to use the gstacks output of my run with stacks2.0 to output the vcf file?

This is sort of unrelated, but still relevant to mention. Using Stacks2.0 with flags -e (restriction enzyme) and --merge-sites, output SNPs in the exact same site (POS - I have reference aligned data)  but with different locus ID. Should this behavior be prevented using --ordered-export?

Thank you so much!

**Comment by enormandeau** [comment]
Hi. This is not the STACKS site or group. I suggest you ask your question on their Google group.

Take care
