### ISSUE TITLE
00_prepare_lane_info: No such file or directory

### ISSUE THREAD

**Issue by menegidio-lab** [enormandeau/stacks_workflow#38]
**Copy your raw files - OK**
**Preparing the lane_info.txt file - FAIL**

This file will contain the names of the raw data files and is used by stacks_workflow later. From the stacks_workflow folder, run:

./00-scripts/00_prepare_lane_info.sh

ERROR:

cp: cannot create regular file '10-log_files/2021-07-29_16h00m18s_00_prepare_lane_info.sh': No such file or directory
./00_prepare_lane_info.sh: line 17: 01-info_files/lane_info.txt: No such file or directory

**Environment:**

Ubuntu Server 20.04
Conda with all dependencies installed.

**Comment by enormandeau** [comment]
Hi.

I don't have enough information to help you with this error report.

Could you install `ncdu`, go to your stacks_workflow folder and type `ncdu -o stacks_workflow.ncdu` then share the file either here or by email?
