### ISSUE TITLE
how to modify the cutoff value?  

### ISSUE THREAD

**Issue by nods-sparrow** [enormandeau/stacks_workflow#39]
In the fifth section 'Explore SNP duplication using the following scripts', i don't know how to modify the cutoff value. i can understand the type of cutoff value 'Fis < -0.1', but i  can't figure out the other type 'Fis + MedRatio < 0.1; Fis + MedRatio*3 < 0.78 ; Fis + MedRatio*8 < 2.3'. What do these inequalitys mean? how to get the cutoff values?

**Comment by enormandeau** [comment]
Hi. Sorry for the long delay in replying.

The best thing you can do is to disable all but one of these filters and play with each independently to see what they do. I added them to be able to annotate duplicated markers more precisely than with only a vertical split. These have different slopes.

**Comment by nods-sparrow** [comment]
Thank you very much~
